version: 2
jobs:
    build:
      docker: 
        - image: circleci/node:7.10 # the primary container, where your job's commands are run
      
      workiworking_directory: ~/repo
      steps:
        - checkout # check out the code in the project directory
        - restore_cache:
            keys:
              - v1-dependencies-{{ checksum "package.json" }}
              - v1-dependencies  
        - run: yarn install
        - save_cache:
            paths:
              - node_modules
            key: v1-dependencies-{{ checksum "package.json" }}